#!/bin/bash

cd tools ; git pull ; cd ..

cp ./tools/makefile makefile

backup_folder=".backup_tools/$(date +"%Y-%m-%d_%H:%M:%S")"
mkdir -p "${backup_folder}"

# backup eslint config
mv eslint.config.js "${backup_folder}/eslint.config.js"

# copy files
cp ./tools/eslint.config.js eslint.config.js
cp -r ./tools/.vscode ./.vscode

# setup eslint
ni -D eslint @antfu/eslint-config simple-git-hooks eslint-plugin-format
